/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applaporan;

import controller.MainController;
import static controller.MainController.notifikasi_c_barang;
import static controller.MainController.notifikasi_d_barang;
import static controller.MainController.notifikasi_u_barang;
import controller.Otentikasi;
import static controller.Otentikasi.getGrant;
import static databases.CrudModel.createDataBarang;
import static databases.CrudModel.deleteDataBarang;
import static databases.CrudModel.readDataBarang;
import static databases.CrudModel.updateDataBarang;
import javax.swing.JOptionPane;

/**
 *
 * @author Rifky <qnoy.rifky@gmail.com>
 */
public class Form_master_barang extends javax.swing.JFrame {
    Otentikasi otentikasi = new Otentikasi();
    MainController frame = new MainController();
    public int total_barang = 0;

    /**
     * Creates new form Form_master_barang
     */
    public Form_master_barang() {
        if (getGrant()) {
            initComponents();
            readDataBarang(null, null, jTable_barang);
            total_barang = jTable_barang.getRowCount();
            total_data_brg.setText(String.valueOf(total_barang));
            btn_fbrg_hapus.setEnabled(false);
            btn_brg_ubah.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "silahkan login dahulu", "tidak ada akses", 2);
            frame.showLoginApp();
        }
    

}

private void bersih(){
        txt_brg_nm_barang.setText("");
        cb_brg_kategori.setSelectedIndex(0);
        txt_brg_harga.setText("");
        btn_fbrg_hapus.setEnabled(false);
        btn_brg_ubah.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_brg_ubah = new javax.swing.JButton();
        txt_brg_nm_barang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_brg_harga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_barang = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_fbrg_hapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_brg_cari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_brg_kategori = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        total_data_brg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_brg_satuan = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_brg_ubah.setBackground(btn_tambah.getBackground());
        btn_brg_ubah.setForeground(btn_tambah.getForeground());
        btn_brg_ubah.setText("ubah");
        btn_brg_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brg_ubahActionPerformed(evt);
            }
        });

        txt_brg_nm_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brg_nm_barangActionPerformed(evt);
            }
        });

        jLabel1.setText("data");

        jLabel2.setText("Barang");

        jLabel3.setText("nama barang");

        jTable_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id barang", "nama barang", "kategori", "harga", "satuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_barang.getTableHeader().setReorderingAllowed(false);
        jTable_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_barang);
        if (jTable_barang.getColumnModel().getColumnCount() > 0) {
            jTable_barang.getColumnModel().getColumn(0).setResizable(false);
            jTable_barang.getColumnModel().getColumn(1).setResizable(false);
            jTable_barang.getColumnModel().getColumn(2).setResizable(false);
            jTable_barang.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_tambah.setBackground(new java.awt.Color(244, 51, 51));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_fbrg_hapus.setBackground(btn_tambah.getBackground());
        btn_fbrg_hapus.setForeground(btn_tambah.getForeground());
        btn_fbrg_hapus.setText("hapus");
        btn_fbrg_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fbrg_hapusActionPerformed(evt);
            }
        });

        jButton4.setBackground(btn_tambah.getBackground());
        jButton4.setForeground(btn_tambah.getForeground());
        jButton4.setText("cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("kategori");

        cb_brg_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Beverage", "Food", "Paket", "Additional barang", "Material" }));

        jLabel6.setText("harga");

        jLabel7.setText("Total :");

        total_data_brg.setText("0");

        jLabel8.setText("satuan");

        cb_brg_satuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "kantong", "kg", "liter", "Pack", "lembar", "pcs", "carton", "pcs", "roll", "buku" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_brg_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btn_fbrg_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_brg_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_brg_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_brg_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_brg_nm_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb_brg_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_data_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_brg_nm_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_brg_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_brg_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_brg_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_brg_ubah)
                    .addComponent(btn_fbrg_hapus)
                    .addComponent(btn_tambah))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_brg_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_data_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_brg_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brg_ubahActionPerformed
        // TODO add your handling code here:
        int bar = jTable_barang.getSelectedRow();
        int col1 = Integer.parseInt(jTable_barang.getModel().getValueAt(bar, 0).toString());
        updateDataBarang(col1);
        if (notifikasi_u_barang) {
            JOptionPane.showMessageDialog(this, "data berhasil di ubah", "notifikasi", 1);
        } else {
            JOptionPane.showMessageDialog(this, "data gagal di ubah", "notifikasi", 2);
        }
        readDataBarang(null, null, jTable_barang);
        bersih();
    }//GEN-LAST:event_btn_brg_ubahActionPerformed

    private void txt_brg_nm_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brg_nm_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brg_nm_barangActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        createDataBarang();
        if (notifikasi_c_barang) {
            JOptionPane.showMessageDialog(this, "data berhasil di tambah", "notifikasi", 1);
        } else {
            JOptionPane.showMessageDialog(this, "data gagal di tambah", "notifikasi", 2);
        }
        readDataBarang(null, null, jTable_barang);
        bersih();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_fbrg_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fbrg_hapusActionPerformed
        // TODO add your handling code here:
        int bar = jTable_barang.getSelectedRow();
        int col1 = Integer.parseInt(jTable_barang.getModel().getValueAt(bar, 0).toString());
        int result = JOptionPane.showConfirmDialog(this, "Hapus data " + col1 + " ?", this.getTitle(), JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            deleteDataBarang(col1);
            if (notifikasi_d_barang) {
                readDataBarang(null, null, jTable_barang);
                JOptionPane.showMessageDialog(this, "data berhasil di hapus", "notifikasi", 1);
            } else {
                JOptionPane.showMessageDialog(this, "data berhasil di hapus", "notifikasi", 2);
            }

        } else if (result == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        }
        bersih();
    }//GEN-LAST:event_btn_fbrg_hapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tangkap_val = txt_brg_cari.getText();
  
        if (!tangkap_val.isEmpty()) {
            readDataBarang(null, tangkap_val, jTable_barang);
        }else{
            JOptionPane.showMessageDialog(this, "kolom cari tidak boleh kosong", "notifikasi", 3);
            readDataBarang(null, null, jTable_barang);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_barangMouseClicked
        // TODO add your handling code here:
        int bar = jTable_barang.getSelectedRow();
        int col1 = Integer.parseInt(jTable_barang.getModel().getValueAt(bar, 0).toString());
        String col2 = jTable_barang.getModel().getValueAt(bar, 1).toString();
        String col3 = jTable_barang.getModel().getValueAt(bar, 2).toString();
        String col4 = jTable_barang.getModel().getValueAt(bar, 3).toString();
        String col5 = jTable_barang.getModel().getValueAt(bar, 4).toString();

        txt_brg_nm_barang.setText(col2);
        cb_brg_kategori.setSelectedItem(col3);
        cb_brg_satuan.setSelectedItem(col5);
        txt_brg_harga.setText(col4);
        btn_fbrg_hapus.setEnabled(true);
        btn_brg_ubah.setEnabled(true);
    }//GEN-LAST:event_jTable_barangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_master_barang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_master_barang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_master_barang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_master_barang.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_master_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_brg_ubah;
    private javax.swing.JButton btn_fbrg_hapus;
    private javax.swing.JButton btn_tambah;
    public static javax.swing.JComboBox<String> cb_brg_kategori;
    public static javax.swing.JComboBox<String> cb_brg_satuan;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_barang;
    private javax.swing.JLabel total_data_brg;
    private javax.swing.JTextField txt_brg_cari;
    public static javax.swing.JTextField txt_brg_harga;
    public static javax.swing.JTextField txt_brg_nm_barang;
    // End of variables declaration//GEN-END:variables
}
